#! /bin/sh
# /etc/init.d/intercomjs

### BEGIN INIT INFO
# Provides:          intercomjs
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the intercom js service
# Description:       Starts Darkice and the node forever server
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
app=/root/intercomjs/app/js
logfile=/root/log_intercomjs_express.log
case "$1" in
  start)
    echo "Starting Darkice"
    start-stop-daemon --start --background --exec /usr/bin/darkice
    echo "Starting node forever"
    PATH=/usr/local/bin:$PATH
    export NODE_ENV=/usr/local/bin/node
    PORT=80 forever start -l $logfile -a $app
    ;;
  restart)
    echo "Restarting Darkice"

    start-stop-daemon --stop --oknodo --quiet --exec /usr/bin/darkice
    start-stop-daemon --start --background --exec /usr/bin/darkice

    echo "Restarting Forever app"
    /usr/local/bin/forever restartall
    ;;
  status)
    /usr/local/bin/forever list
    ;;
  stop)
    echo "stop all node apps via forever"
    /usr/local/bin/forever stopall

    echo "stopping darkice"
    start-stop-daemon --stop --oknodo --quiet --exec /usr/bin/darkice
    ;;
  *)
    echo "Usage: /etc/init.d/intercomjs {start|restart|stop|status}"
    exit 1
    ;;
esac

exit 0
