#! /bin/sh
# /etc/init.d/intercomjs

### BEGIN INIT INFO
# Provides:          intercomjs
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the intercom js service
# Description:       Starts Darkice and the node forever server
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Darkice"
    start-stop-daemon --start --background --exec /usr/bin/darkice
    echo "Starting node forever"
    PORT=80 /root/intercomjs/node_modules/.bin/forever start /root/intercomjs/app.js -l /root/log_intercomjs_express.log
    ;;
  stop)
    echo "stop all node apps"
    #
    /root/intercomjs/node_modules/.bin/forever stopall
    echo "stopping darkice"
    start-stop-daemon --stop --oknodo --quiet --exec /usr/bin/darkice

    ;;
  *)
    echo "Usage: /etc/init.d/noip {start|stop}"
    exit 1
    ;;
esac

exit 0
